name: ed_server
description: A server app using the shelf package and Docker.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_web_socket: ^2.0.0
  crypto: ^3.0.3
  hex: ^0.2.0
  postgres: ^3.4.0
  televerse: ^1.26.1
  # uuid: ^4.5.1
  solana: ^0.31.0
  http: ^1.2.2

  # http: ^1.2.1
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
